### PR TITLE
zephyr: Aligning source directory tree with apache/mynewt-core

### PR DESCRIPTION
**Pull request by de-nordic**
Goal of this commit is to make file structure tree, of this fork of
TinyCBOR, to be more aligned to the upstream:
https://github.com/apache/mynewt-core/tree/master/encoding/tinycbor

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

### CODE REVIEW

**Comment by carlescufi** [comment]
cc @vrahane @mlaz @ccollins476ad

**Review by mlaz — APPROVED** [review]
Looks good to me.

**Comment by nvlsianpu** [comment]
@de-nordic Can you provide path to the zephyr west.yaml https://docs.zephyrproject.org/latest/guides/modules.html#changes-to-existing-modules and any code adaptation needed?
(zephyr/include/mgmt/buf.h)

**Comment by de-nordic** [comment]
@nvlsianpu synchronous modification of zephyr source code is not needed for now, as there is redundant path provided that makes old includes work within zephyr (in CMakeLists.txt). Such changes may be completed lately. Redundant path may be removed lately as there is more work needed  within TinyCBOR code alignment.

**Comment by de-nordic** [comment]
@nvlsianpu west.yml update: https://github.com/zephyrproject-rtos/zephyr/pull/19876

**Review by vrahane — APPROVED** [review]

**Review by nvlsianpu — APPROVED** [review]
looks good. I also verified that it actually works well as part of smp_svr application (so tinycbor user was mcumgr) and mcuboot.

**Comment by nvlsianpu** [comment]
@carlescufi this is ready to be merged

**Pull request merged**
